stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running unit tests..."
  after_script:
    - echo "Cleaning up temporary files... "

run_lint_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running lint tests..."
  after_script:
    - echo "Cleaning up temporary files... "

build_image:
  stage: build
  script:
    - wrong-command "Building the docker image..."
    - echo "Tagging the docker image"

push_image:
  stage: build
  needs:
    - build_image
  script:
    - echo "Logging into docker registry..."
    - echo "Pushing docker image to registry..."
<<<<<<< HEAD
=======

deploy_image:
  stage: deploy
  script:
    - echo "Deploying new docker image to dev server..."
>>>>>>> 4a462fe (put it into stages and added needs as one stage depends on second like build image and push image)
